on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - run: pip install -r requirements.txt

      - run: npm install aws-cdk@2.78.0 -g

      - run: echo $SUBSCRIPTIONS_YAML > subscriptions.yaml
        env:
          SUBSCRIPTIONS_YAML: ${{ secrets.SUBSCRIPTIONS_YAML }}

      - run: cdk synth
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
